name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Проверка docker-compose
        run: docker-compose config -q

      - name: Установка NGINX
        run: sudo apt-get update && sudo apt-get install -y nginx

      - name: Проверка nginx.conf
        run: |
          nginx -t -c $(pwd)/nginx.conf || (echo "Ошибка в nginx.conf" && exit 1)
